apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-front
spec:
  selector:
    matchLabels:
      app: test-app
      tier: front
  template:
    metadata:
      labels:
        app: test-app
        tier: front
    spec:
      containers:
        - name: test-front
          image: public.ecr.aws/p4g1u1f9/23724-k8s/front:16
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-front
spec:
  type: NodePort
  selector:
    app: test-app
    tier: front
  ports:
    - port: 80
      nodePort: 30000
